# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  push:
    branches: [ release ]

jobs:

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
      - run: yarn install --frozen-lockfile && yarn build && yarn test && yarn doc:html
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            node-version: 12
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/docs
